### ISSUE TITLE
iOS build

### ISSUE THREAD

**Issue by nighto** [jfoclpf/bike-reporter#2]
I don't have an Android but an iPhone, so I'll see what would need to be changed to have it running on iOS.

**Comment by nighto** [comment]
Tried adding platform `iOS`, got this error:

```
arlindo.pereira@nb-apereira bike-reporter % cordova platform add ios   
Using cordova-fetch for cordova-ios@^6.1.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: bike.reporter
	Name: Bike Reporter
iOS project created with cordova-ios@6.1.1
Installing "cordova-pdf-generator" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-pdf-generator': CordovaError: Uh oh!
"/Users/arlindo.pereira/src/bike-reporter/plugins/cordova-pdf-generator/src/ios/PDFGenerator.m" not found!
    at copyFile (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/lib/plugman/pluginHandlers.js:309:36)
    at copyNewFile (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/lib/plugman/pluginHandlers.js:335:5)
    at installHelper (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/lib/plugman/pluginHandlers.js:259:13)
    at install (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at ActionStack.process (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:142:21)
    at Api.addPlugin (/Users/arlindo.pereira/src/bike-reporter/platforms/ios/cordova/Api.js:254:10)
    at handleInstall (/Users/arlindo.pereira/.nvm/versions/node/v12.18.3/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:561:10)
    at /Users/arlindo.pereira/.nvm/versions/node/v12.18.3/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:344:28
```

**Comment by nighto** [comment]
Tried adding the plugin manually but got the same error. Not sure what to do.

**Comment by jfoclpf** [comment]
Boas, confesso que nunca testei em ios, podes sff dar o output de

`cordova platform`

e, caso ios esteja listado, depois de

`cordova clean && cordova build ios`

**Comment by jfoclpf** [comment]
@nighto sempre conseguiste?
Também me esqueci: chegaste a fazer `npm install`?

**Comment by jfoclpf** [comment]
Agora basta fazeres

```
git clone https://github.com/jfoclpf/bike-reporter.git
cd bike-reporter
cordova platform add ios
cd platforms/ios
pod update
open Bike\ Reporter.xcworkspace/
```
